### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/open-leadership-training-series#24]
@flukeout can you do a brief review of this some day? https://mzl.la/open-leadership

**Comment by flukeout** [comment]
@xmatthewx definitely, do you have permissions to assign this to me here, I'm not able to.

**Comment by xmatthewx** [comment]
@acabunoc – can you assign? add the mofo admin team to this repo?

**Comment by abbycabs** [comment]
Added the team!

**Comment by flukeout** [comment]
@acabunoc - so I think I'll make a fork of this, and then submit a PR with some style changes, does that work?

**Comment by abbycabs** [comment]
That is perfect, thanks @flukeout!

**Comment by flukeout** [comment]
Hey @acabunoc having some trouble getting set up.. 

``bundle install`` was complaining that I need ruby 2.2.2, and after installing that version of ruby, it throws this error now...

```
mozyvr-20687:open-leadership-training-series mozilla$ bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'bundler' (>= 0) among 16 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/local/bin/bundle:22:in `<main>'
```

**Comment by flukeout** [comment]
New problem, I've got ruby 2.2.2 running, but bundler says I'm running an incompatible version..

```
mozyvr-20687:open-leadership-training-series mozilla$ bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies....
activesupport-5.0.0.1 requires ruby version >= 2.2.2, which is incompatible with the current version, ruby 2.0.0p648

mozyvr-20687:open-leadership-training-series mozilla$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
```

**Comment by flukeout** [comment]
Sorted!

**Comment by xmatthewx** [comment]
🌷  Thanks you two. Looks fab! 🌷
